// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renova.Data;

namespace Renova.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200514022419_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Renova.Models.Gallery.Project", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Images")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Name");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Name = "Duggan",
                            Images = "/images/gallery/Duggan/after/duggan_after_kitchen2.jpg;/images/gallery/Duggan/after/duggan_after_kitchen5.jpg;/images/gallery/Duggan/after/duggan_after_livingroom3.jpg;/images/gallery/Duggan/after/duggan_after_bathroom2.jpg;/images/gallery/Duggan/after/duggan_after_livingroom.jpg;/images/gallery/Duggan/after/duggan_after_wideshot.jpg;/images/gallery/Duggan/after/duggan_after_diningarea.jpg;/images/gallery/Duggan/after/duggan_after_kitchen1.jpg;/images/gallery/Duggan/after/duggan_after_kitchen4.jpg;/images/gallery/Duggan/after/duggan_after_kitchen3.jpg;/images/gallery/Duggan/after/duggan_after_bathroom.jpg;/images/gallery/Duggan/after/duggan_after_decoratedwide.jpg;/images/gallery/Duggan/after/duggan_after_livingroom2.jpg;/images/gallery/Duggan/after/duggan_after_backentrance.jpg"
                        },
                        new
                        {
                            Name = "Millwoods",
                            Images = "/images/gallery/Millwoods/after/millwoods_after_bathroom1.jpg;/images/gallery/Millwoods/after/millwoods_after_dining1.jpg;/images/gallery/Millwoods/after/millwoods_after_bathroom3.jpg;/images/gallery/Millwoods/after/millwoods_after_kitchen2.jpg;/images/gallery/Millwoods/after/millwoods_after_bathroom2.jpg;/images/gallery/Millwoods/after/millwoods_after_kitchen1.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
