// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renova.Data;

#nullable disable

namespace Renova.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Renova.Models.Gallery.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullImages")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailImages")
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            DisplayName = "Before and After Gallery",
                            FullImages = "/images/gallery/before-after/full-resolution/0_duggan_before_bathroom.jpg;/images/gallery/before-after/full-resolution/1_duggan_after_bathroom.jpg;/images/gallery/before-after/full-resolution/2_duggan_before_livingroom.jpg;/images/gallery/before-after/full-resolution/3_duggan_after_livingroom.jpg;/images/gallery/before-after/full-resolution/4_duggan_before_kitchen.jpg;/images/gallery/before-after/full-resolution/5_duggan_after_kitchen.jpg",
                            Name = "before-after",
                            ThumbnailImage = "",
                            ThumbnailImages = "/images/gallery/before-after/thumbnails/0_duggan_before_bathroom.jpg;/images/gallery/before-after/thumbnails/1_duggan_after_bathroom.jpg;/images/gallery/before-after/thumbnails/2_duggan_before_livingroom.jpg;/images/gallery/before-after/thumbnails/3_duggan_after_livingroom.jpg;/images/gallery/before-after/thumbnails/4_duggan_before_kitchen.jpg;/images/gallery/before-after/thumbnails/5_duggan_after_kitchen.jpg"
                        },
                        new
                        {
                            ProjectId = 2,
                            DisplayName = "Duggan Project",
                            FullImages = "/images/gallery/duggan/full-resolution/duggan_after_backentrance.jpg;/images/gallery/duggan/full-resolution/duggan_after_bathroom.jpg;/images/gallery/duggan/full-resolution/duggan_after_bathroom2.jpg;/images/gallery/duggan/full-resolution/duggan_after_decoratedwide.jpg;/images/gallery/duggan/full-resolution/duggan_after_diningarea.jpg;/images/gallery/duggan/full-resolution/duggan_after_kitchen1.jpg;/images/gallery/duggan/full-resolution/duggan_after_kitchen2.jpg;/images/gallery/duggan/full-resolution/duggan_after_kitchen3.jpg;/images/gallery/duggan/full-resolution/duggan_after_kitchen4.jpg;/images/gallery/duggan/full-resolution/duggan_after_kitchen5.jpg;/images/gallery/duggan/full-resolution/duggan_after_livingroom.jpg;/images/gallery/duggan/full-resolution/duggan_after_livingroom2.jpg;/images/gallery/duggan/full-resolution/duggan_after_livingroom3.jpg;/images/gallery/duggan/full-resolution/duggan_after_wideshot.jpg",
                            Name = "duggan",
                            ThumbnailImage = "",
                            ThumbnailImages = "/images/gallery/duggan/thumbnails/duggan_after_backentrance.jpg;/images/gallery/duggan/thumbnails/duggan_after_bathroom.jpg;/images/gallery/duggan/thumbnails/duggan_after_bathroom2.jpg;/images/gallery/duggan/thumbnails/duggan_after_decoratedwide.jpg;/images/gallery/duggan/thumbnails/duggan_after_diningarea.jpg;/images/gallery/duggan/thumbnails/duggan_after_kitchen1.jpg;/images/gallery/duggan/thumbnails/duggan_after_kitchen2.jpg;/images/gallery/duggan/thumbnails/duggan_after_kitchen3.jpg;/images/gallery/duggan/thumbnails/duggan_after_kitchen4.jpg;/images/gallery/duggan/thumbnails/duggan_after_kitchen5.jpg;/images/gallery/duggan/thumbnails/duggan_after_livingroom.jpg;/images/gallery/duggan/thumbnails/duggan_after_livingroom2.jpg;/images/gallery/duggan/thumbnails/duggan_after_livingroom3.jpg;/images/gallery/duggan/thumbnails/duggan_after_wideshot.jpg"
                        },
                        new
                        {
                            ProjectId = 3,
                            DisplayName = "Millwoods Project",
                            FullImages = "/images/gallery/millwoods/full-resolution/millwoods_after_bathroom1.jpg;/images/gallery/millwoods/full-resolution/millwoods_after_bathroom2.jpg;/images/gallery/millwoods/full-resolution/millwoods_after_bathroom3.jpg;/images/gallery/millwoods/full-resolution/millwoods_after_dining1.jpg;/images/gallery/millwoods/full-resolution/millwoods_after_kitchen1.jpg;/images/gallery/millwoods/full-resolution/millwoods_after_kitchen2.jpg",
                            Name = "millwoods",
                            ThumbnailImage = "",
                            ThumbnailImages = "/images/gallery/millwoods/thumbnails/millwoods_after_bathroom1.jpg;/images/gallery/millwoods/thumbnails/millwoods_after_bathroom2.jpg;/images/gallery/millwoods/thumbnails/millwoods_after_bathroom3.jpg;/images/gallery/millwoods/thumbnails/millwoods_after_dining1.jpg;/images/gallery/millwoods/thumbnails/millwoods_after_kitchen1.jpg;/images/gallery/millwoods/thumbnails/millwoods_after_kitchen2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
